#!/bin/bash
# Creates build directories for a set of compilers given as command line
# parameters:
# ./build_init g++-4.6.4 g++-4.7.2 g++-4.8.1 clang++

for compiler in $*; do
    # OpenCL backend
    mkdir build-cl-${compiler}
    pushd build-cl-${compiler}
    CXX=${compiler} cmake        \
        -DVEXCL_CACHE_KERNELS=ON \
        -DVEXCL_BACKEND=OpenCL   \
        -G Ninja                 \
        ..
    popd

    if which nvcc; then
        # CUDA backend
        mkdir build-cu-${compiler}
        pushd build-cu-${compiler}
        CXX=${compiler} cmake        \
            -DVEXCL_BACKEND=CUDA     \
            -G Ninja                 \
            ..
        popd
    fi
done
