#!/bin/bash
# Creates build directories for a set of compilers given as command line
# parameters:
# ./build_init g++-4.6.4 g++-4.7.2 g++-4.8.1 clang++

for compiler in $*; do
    for backend in OpenCL Compute CUDA JIT; do
        mkdir build-${backend,,}-${compiler}
        pushd build-${backend,,}-${compiler}
        CXX=${compiler} cmake          \
            -DCMAKE_BUILD_TYPE=Release \
            -DVEXCL_CACHE_KERNELS=ON   \
            -DVEXCL_BACKEND=${backend} \
            -G Ninja                   \
            ..
        popd
    done
done
