#!/bin/bash

# Builds everything within all configured build directories and runs the tests
# under given OpenCL and CUDA platforms.

# Stop on errors:
#set -e

# Build with every possible compiler:
for backend in OpenCL Compute; do
    for dir in build-${backend,,}-*; do
        ninja -C ${dir}

        platforms=$(${dir}/examples/devlist | grep -a CL_PLATFORM_NAME | sed 's/.*= \(\w*\).*/\1/' | sort -u)

        # and run the tests for each OpenCL platform:
        for platform in ${platforms}; do
            echo
            echo "----------------------------------------------------------------------"
            echo "Backend=${backend} OCL_PLATFORM=${platform} Test=${dir}"
            echo "----------------------------------------------------------------------"
            echo
            OCL_PLATFORM=${platform} ninja -C ${dir} test
        done
    done
done

# Run tests for the CUDA backend built with every possible compiler:
for dir in build-cuda-*; do
    echo
    echo "----------------------------------------------------------------------"
    echo "Backend=CUDA Test=${dir}"
    echo "----------------------------------------------------------------------"
    echo
    ninja -C ${dir}
    ninja -C ${dir} test
done

# Run tests for the JIT backend built with every possible compiler:
for dir in build-jit-*; do
    echo
    echo "----------------------------------------------------------------------"
    echo "Backend=JIT Test=${dir}"
    echo "----------------------------------------------------------------------"
    echo
    ninja -C ${dir}
    ninja -C ${dir} test
done
