VexCL: vex::SpMat< val_t, col_t, idx_t > Class Template Reference
vex::SpMat< val_t, col_t, idx_t > Class Template Reference
Sparse matrix in hybrid ELL-CSR format.
#include <spmat.hpp>
Public Types
typedef val_t value_type
typedef cl_scalar_of< val_t >::type scalar_type
Public Member Functions
SpMat ()
Empty constructor.
SpMat (const std::vector< backend::command_queue > &queue, size_t n, size_t m, const idx_t *row, const col_t *col, const val_t *val)
Constructor.
void apply (const vex::vector< val_t > &x, vex::vector< val_t > &y, scalar_type alpha=1, bool append=false) const
Matrix-vector multiplication.
size_t rows () const
Number of rows.
size_t cols () const
Number of columns.
size_t nonzeros () const
Number of non-zero entries.
Static Public Member Functions
static void inline_preamble (backend::source_generator &src, const backend::command_queue &queue, const std::string &prm_name, detail::kernel_generator_state_ptr)
static void inline_expression (backend::source_generator &src, const backend::command_queue &queue, const std::string &prm_name, detail::kernel_generator_state_ptr)
static void inline_parameters (backend::source_generator &src, const backend::command_queue &queue, const std::string &prm_name, detail::kernel_generator_state_ptr)
static void inline_arguments (backend::kernel &kernel, unsigned part, size_t, const SpMat &A, const vector< val_t > &x, detail::kernel_generator_state_ptr)
Detailed Description
template<typename val_t, typename col_t = size_t, typename idx_t = size_t>
class vex::SpMat< val_t, col_t, idx_t >
Sparse matrix in hybrid ELL-CSR format.
Constructor & Destructor Documentation
template<typename val_t, typename col_t = size_t, typename idx_t = size_t> vex::SpMat< val_t, col_t, idx_t >::SpMat (const std::vector< backend::command_queue > & queue, size_t n, size_t m, const idx_t * row, const col_t * col, const val_t * val) inline
Constructor.
Constructs GPU representation of the matrix. Input matrix is in CSR format. GPU matrix utilizes ELL format and is split equally across all compute devices. When there are more than one device, secondary queue can be used to perform transfer of ghost values across GPU boundaries in parallel with computation kernel.
Parameters
queue vector of queues. Each queue represents one compute device.
n number of rows in the matrix.
m number of cols in the matrix.
row row index into col and val vectors.
col column numbers of nonzero elements of the matrix.
val values of nonzero elements of the matrix.
References vex::backend::cuda::duplicate_queue(), vex::backend::cuda::is_cpu(), and vex::partition().
Member Function Documentation
template<typename val_t, typename col_t = size_t, typename idx_t = size_t> void vex::SpMat< val_t, col_t, idx_t >::apply (const vex::vector< val_t > & x, vex::vector< val_t > & y, scalar_type alpha = 1, bool append = false) const inline
Matrix-vector multiplication.
Matrix vector multiplication (or) is performed in parallel on all registered compute devices. Ghost values of x are transfered across GPU boundaries as needed.
Parameters
x input vector.
y output vector.
alpha coefficient in front of matrix-vector product
append if set, matrix-vector product is appended to y. Otherwise, y is replaced with matrix-vector product.
References vex::vector< T >::begin(), vex::SpMat< val_t, col_t, idx_t >::cols(), vex::copy(), vex::vector< T >::end(), vex::permutation(), and vex::backend::cuda::select_context().
Referenced by vex::device_spmv_perf().
The documentation for this class was generated from the following file:
vexcl/spmat.hpp