VexCL: vex::multivector< T, N > Class Template Reference
vex::multivector< T, N > Class Template Reference
Container classes
Container for several vex::vectors.
#include <multivector.hpp>
Inherits multivector_terminal_expression.
Classes
class const_element
Proxy class.
class element
Proxy class.
Public Types
typedef vex::vector< T > subtype
typedef std::array< T, N > value_type
typedef T sub_value_type
typedef iterator_type< multivector, element > iterator
typedef iterator_type< const multivector, const_element > const_iterator
Public Member Functions
multivector (const std::vector< backend::command_queue > &queue, const std::vector< T > &host, backend::mem_flags flags=backend::MEM_READ_WRITE)
Constructor.
multivector (const std::vector< backend::command_queue > &queue, size_t size, const T *host=0, backend::mem_flags flags=backend::MEM_READ_WRITE)
Constructor.
multivector (size_t size)
Construct from size.
multivector (const multivector &mv)
Copy constructor.
multivector (multivector &&mv) noexcept
Move constructor.
void resize (const std::vector< backend::command_queue > &queue, size_t size)
Resize multivector.
void resize (size_t size)
Resize multivector.
void clear ()
Fills multivector with zeros.
size_t size () const
Return size of a multivector (equals size of individual components).
const vex::vector< T > & operator() (size_t i) const
Returns multivector component.
vex::vector< T > & operator() (size_t i)
Returns multivector component.
const_iterator begin () const
Const iterator to beginning.
iterator begin ()
Iterator to beginning.
const_iterator end () const
Const iterator to end.
iterator end ()
Iterator to end.
const_element operator[] (size_t i) const
Returns elements of all vectors, packed in std::array.
element operator[] (size_t i)
Assigns elements of all vectors to a std::array value.
const std::vector< backend::command_queue > & queue_list () const
Return reference to multivector's queue list.
const multivector & operator= (const multivector &mv)
Assignment to a multivector.
template<class Expr >
const multivector & operator= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator+= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator-= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator*= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator/= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator%= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator&= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator|= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator^= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator<<= (const Expr &expr)
Multivector expression assignment.
template<class Expr >
const multivector & operator>>= (const Expr &expr)
Multivector expression assignment.
Static Public Attributes
static const size_t NDIM = N
Detailed Description
template<typename T, size_t N>
class vex::multivector< T, N >
Container for several vex::vectors.
This class allows to synchronously operate on several vex::vectors of the same type and size.
Constructor & Destructor Documentation
template<typename T, size_t N> vex::multivector< T, N >::multivector (const std::vector< backend::command_queue > & queue, const std::vector< T > & host, backend::mem_flags flags = backend::MEM_READ_WRITE) inline
Constructor.
If host pointer is not NULL, it is copied to the underlying vector components of the multivector.
Parameters
queue queue list to be shared between all components.
host Host vector that holds data to be copied to the components. Size of host vector should be divisible by N. Components of the created multivector will have size equal to host.size() / N. The data will be partitioned equally between all components.
flags device memory creation flags.
References vex::multivector< T, N >::resize(), and vex::multivector< T, N >::size().
template<typename T, size_t N> vex::multivector< T, N >::multivector (const std::vector< backend::command_queue > & queue, size_t size, const T * host = 0, backend::mem_flags flags = backend::MEM_READ_WRITE) inline
Constructor.
If host pointer is not NULL, it is copied to the underlying vector components of the multivector.
Parameters
queue queue list to be shared between all components.
size Size of each component.
host Pointer to host buffer that holds data to be copied to the components. Size of the buffer should be equal to N * size. The data will be partitioned equally between all components.
flags device memory creation flags.
References vex::multivector< T, N >::resize().
Member Function Documentation
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator%= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator&= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator*= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator+= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator-= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator/= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator<<= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator>>= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator^= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
template<typename T, size_t N> template<class Expr > const multivector& vex::multivector< T, N >::operator|= (const Expr & expr)
Multivector expression assignment.
All operations are delegated to components of the multivector.
The documentation for this class was generated from the following file:
vexcl/multivector.hpp