VexCL: vex::clogs Namespace Reference
vex::clogs Namespace Reference
Wrappers for the clogs library.
Classes
struct clogs_type
Maps a compile-time C type to a clogs type structure.
struct is_clogs_type
Whether T can be mapped to a clogs type.
struct is_scannable
Whether T can be used for exclusive_scan.
struct is_sort_key
Whether T can be used as a key type for sort or stable_sort_by_key.
Functions
template<typename T >
void exclusive_scan (const vex::vector< T > &src, vex::vector< T > &dst, const T &init=T())
Perform exclusive scan using clogs.
template<typename K >
void sort (vex::vector< K > &keys)
Perform sort using clogs.
template<typename K , typename V >
void stable_sort_by_key (vex::vector< K > &keys, vex::vector< V > &values)
Perform stable sort of keys and values using clogs.
Detailed Description
Wrappers for the clogs library.
Function Documentation
template<typename T > void vex::clogs::exclusive_scan (const vex::vector< T > & src, vex::vector< T > & dst, const T & init = T())
Perform exclusive scan using clogs.
It is legal for src and dst to be the same vector, in which case an in-place scan is performed.
References vex::vector< T >::part_size(), vex::vector< T >::part_start(), and vex::vector< T >::queue_list().
template<typename K > void vex::clogs::sort (vex::vector< K > & keys)
Perform sort using clogs.
If there are more than one device in vector's queue list, then all partitions are sorted individually on devices and then merged on the host.
References vex::vector< T >::part_size(), and vex::vector< T >::queue_list().
template<typename K , typename V > void vex::clogs::stable_sort_by_key (vex::vector< K > & keys, vex::vector< V > & values)
Perform stable sort of keys and values using clogs.
If there are more than one device in vector's queue list, then all partitions are sorted individually on devices and then merged on the host.
References vex::vector< T >::part_size(), and vex::vector< T >::queue_list().