VexCL: vex::backend::opencl Namespace Reference
vex::backend::opencl Namespace Reference
The OpenCL backend.
Typedefs
typedef cl::Context context
typedef cl::Device device
typedef cl::CommandQueue command_queue
typedef cl_command_queue_properties command_queue_properties
typedef cl_device_id device_id
typedef cl::NDRange ndrange
typedef cl_mem_flags mem_flags
typedef cl::Error error
Functions
void save_program_binaries (const std::string &hash, const cl::Program &program, const std::string &source)
Saves program binaries for future reuse.
boost::optional< cl::Program > load_program_binaries (const std::string &hash, const cl::Context &context, const std::vector< cl::Device > &device)
Tries to read program binaries from file cache.
cl::Program build_sources (const cl::CommandQueue &queue, const std::string &source, const std::string &options="")
Create and build a program from source string.
void select_context (const command_queue &)
Binds the specified context to the calling CPU thread.
device_id get_device_id (const command_queue &q)
Returns id of the device associated with the given queue.
command_queue duplicate_queue (const command_queue &q)
Create command queue on the same context and device as the given one.
bool is_cpu (const command_queue &q)
Checks if the compute device is CPU.
template<class DevFilter >
std::vector< cl::Device > device_list (DevFilter &&filter)
Select devices by given criteria.
template<class DevFilter >
std::pair< std::vector< cl::Context >, std::vector< command_queue > > queue_list (DevFilter &&filter, cl_command_queue_properties properties=0)
Create command queues on devices by given criteria.
Detailed Description
The OpenCL backend.
Function Documentation
cl::Program vex::backend::opencl::build_sources (const cl::CommandQueue & queue, const std::string & source, const std::string & options = "") inline
Create and build a program from source string.
If VEXCL_CACHE_KERNELS macro is defined, then program binaries are cached in filesystem and reused in the following runs.
References load_program_binaries(), save_program_binaries(), and vex::sha1().
template<class DevFilter > std::vector<cl::Device> vex::backend::opencl::device_list (DevFilter && filter)
Select devices by given criteria.
Parameters
filter Device filter functor. Functors may be combined with logical operators.
Returns
list of devices satisfying the provided filter.
This example selects any GPU which supports double precision arithmetic:
auto devices = device_list(
         Filter::Type(CL_DEVICE_TYPE_GPU) && Filter::DoublePrecision
         );
template<class DevFilter > std::pair<std::vector<cl::Context>, std::vector<command_queue> > vex::backend::opencl::queue_list (DevFilter && filter, cl_command_queue_properties properties = 0)
Create command queues on devices by given criteria.
Parameters
filter Device filter functor. Functors may be combined with logical operators.
properties Command queue properties.
Returns
list of queues accociated with selected devices.
See also
device_list
void vex::backend::opencl::select_context (const command_queue &) inline
Binds the specified context to the calling CPU thread.
With the OpenCL backend this is an empty stub provided for compatibility with the CUDA backend.