#ifndef VEXCL_BACKEND_OPENCL_DEFINES_HPP
#define VEXCL_BACKEND_OPENCL_DEFINES_HPP

#ifndef CL_HPP_TARGET_OPENCL_VERSION
#  define CL_HPP_TARGET_OPENCL_VERSION 120
#endif

#ifndef CL_HPP_MINIMUM_OPENCL_VERSION
#  define CL_HPP_MINIMUM_OPENCL_VERSION 120
#endif

#ifndef CL_HPP_ENABLE_EXCEPTIONS
#  define CL_HPP_ENABLE_EXCEPTIONS
#endif

#endif
